org: gurushan
app: auction-service
service: ci-cd-demo

frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-southeast-1

functions:
  hello:
    handler: handler.hello
